Bangla Tutorial Advancing Blog in Python+Django/djangoblog/blogapp/urls.py
from django.urls import path
from . import views


app_name = 'blogapp'

urlpatterns = [
    path('', views.index, name="index"),
    path('author/<name>', views.getauthor, name="author"),
    path('article/<int:id>', views.getsingle, name="single_post"),
    path('topic/<name>', views.getTopic, name="topic"),
    path('create', views.getCreate, name="create"),
    path('profile', views.getProfile, name="profile"),
    path('update/<int:pid>', views.getUpdate, name="update"),
    path('delete/<int:pid>', views.getDelete, name="delete"),
    path('login', views.getLogin, name="login"),
    path('logout', views.getLogout, name="logout"),

    path('register', views.getRegister, name="register"),
    path('topic', views.getCategory, name="category"),
    path('create/topic', views.createTopic, name="createTopic"),


    #account aonfirmations
    path('activate/<uid>/<token>', views.activate, name="activate"),

    path('pdf/<int:id>',views.pdf, name ='pdf')
]


# project/urls.py
#handler404 = 'blogapp.views.handler404'

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blogapp.urls", namespace="blog")),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/templates/base.html
{% load  static %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	<meta name="author" content="FREEHTML5.CO" />

  <!--
	//////////////////////////////////////////////////////

	FREE HTML5 TEMPLATE
	DESIGNED & DEVELOPED by FREEHTML5.CO

	Website: 		http://freehtml5.co/
	Email: 			info@freehtml5.co
	Twitter: 		http://twitter.com/fh5co
	Facebook: 		https://www.facebook.com/fh5co

	//////////////////////////////////////////////////////
	 -->

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="{% static 'favicon.ico' %}">
	<!-- Google Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,400italic|Roboto:400,300,700' rel='stylesheet' type='text/css'>
	<!-- Animate -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon -->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block stylesheet %}

    {% endblock %}

	<style type="text/css">
		#fh5co-offcanvas { width: auto;}
        #fh5co-offcanvas .fh5co-menu, #fh5co-offcanvas .fh5co-bio { width: 400px; padding: 50px;}

	</style>

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<body>

	<div id="fh5co-offcanvas">
		<a href="#" class="fh5co-close-offcanvas js-fh5co-close-offcanvas"><span><i class="icon-cross3"></i> <span>Close</span></span></a>
        {% block profile %}
        {% endblock %}
		<div class="fh5co-menu">
			<div class="fh5co-box">
				<h3 class="heading">Menu</h3>
				<ul>
					<li><a href="#">Blog</a></li>
                    <li><a href="{% url 'blog:category' %}">Category</a> </li>
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'blog:profile' %}">Profile</a> </li>
                        <li><a href="{% url 'blog:logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'blog:login' %}">Login</a></li>
                    {% endif %}
				</ul>
			</div>
			<div class="fh5co-box">
				<h3 class="heading">Search</h3>
				<form action="" method="GET">
					<div class="form-group">
						<input type="text" name="q" class="form-control" placeholder="Type a keyword" value="{{ request.GET.q }}">
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- END #fh5co-offcanvas -->
	<header id="fh5co-header">

		<div class="container-fluid">

			<div class="row">
				<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
				<ul class="fh5co-social">
					<li><a href="#"><i class="icon-twitter"></i></a></li>
					<li><a href="#"><i class="icon-facebook"></i></a></li>
					<li><a href="#"><i class="icon-instagram"></i></a></li>
				</ul>
				<div class="col-lg-12 col-md-12 text-center">
					<h1 id="fh5co-logo"><a href="{% url 'blog:index' %}">Blog</a></h1>
				</div>

			</div>

		</div>

	</header>
<!-- END #fh5co-header -->
	<div class="container-fluid">
		<div class="row fh5co-post-entry">

    {% block content %}


    {% endblock %}
        </div>
    </div>

<footer id="fh5co-footer">
		<p><small>&copy; 2016. Magazine Free HTML5. All Rights Reserverd. <br> Designed by <a href="http://freehtml5.co" target="_blank">FREEHTML5.co</a>  Demo Images: <a href="http://unsplash.com/" target="_blank">Unsplash</a></small></p>
	</footer>



	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'js/main.js' %}"></script>
    {% block script %}

    {% endblock %}
	</body>
</html>

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Welcome to my Bangla blog{% endblock %}
{% block stylesheet %}{% endblock %}
{% block content %}
    <h4 class="container">Category: {{ cat.name }}</h4>
    {% for p in post %}
			<article class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12 animate-box">
				<figure>
					<a href="{% url 'blog:single_post' id=p.id %}"><img src="{{ p.image.url }}" alt="Image" class="img-responsive"></a>
				</figure>
				<span class="fh5co-meta"><a href="{% url 'blog:topic' name=p.category.name %}">{{ p.category.name }}</a></span>
				<h2 class="fh5co-article-title"><a href="{% url 'blog:single_post' id=p.id %}">{{ p.title }}</a></h2>
				<span class="fh5co-meta fh5co-date">{{ p.posted_on }}</span>
			</article>
    {% endfor %}
			<div class="clearfix visible-lg-block visible-md-block visible-sm-block visible-xs-block"></div>




			<div class="clearfix visible-xs-block"></div>
		</div>
	</div>

{% endblock %}

{% block script %}
{% endblock %}

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/templates/confirm_email.html
{% autoescape off %}
Hi {{ user.username }},
Thanks for you Registration in my Blog.
Please click on the link below to confirm your registration,
http://{{ domain }}{% url 'blog:activate' uid=uid token=token %}
{% endautoescape %}

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/templates/crateauthor.html
{% extends 'base.html' %}
{% load  static %}
{% block title %}Create Author Form{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary">Register</button>
    </form>

{% endblock %}

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/templates/create.html
{% extends 'base.html' %}
{% load  static %}
{% block title %} Create new form{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="col-md-8 col-md-offset-4">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-success">Submit</button>
            </form>
        </div>
    </div>

{% endblock %}

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/templates/create_topics.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Create Category{% endblock %}
{% block stylesheet %}{% endblock %}
{% block content %}
    <div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">Create Category</button>
    </form>
    </div>
{% endblock %}

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Welcome to my Bangla blog{% endblock %}
{% block stylesheet %}
     <style>
    .alert{ height: 50px; margin-top: 200px;}
    </style>
{% endblock %}
{% block content %}
       {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}
    {% for p in post %}
			<article class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12 animate-box">
				<figure>
					<a href="{{ p.get_single_url }}"><img src="{{ p.image.url }}" alt="Image" class="img-responsive"></a>
				</figure>
				<span class="fh5co-meta"><a href="{{ p.get_topic_url }}">{{ p.category.name }}</a></span>
				<h2 class="fh5co-article-title"><a href="{{ p.get_single_url }}">{{ p.title }}</a></h2>
                <h4><a href="{{ p.get_author_url }}">{{ p.article_author.name.get_full_name }}</a> </h4>
				<span class="fh5co-meta fh5co-date">{{ p.posted_on }}</span>
			</article>
    {% endfor %}
    <div class="container-fluid">
        <div class="pagination">
            <span class="step-links">
                {% if post.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ post.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
                </span>

                {% if post.has_next %}
                    <a href="?page={{ post.next_page_number }}">next</a>
                    <a href="?page={{ post.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>

{% endblock %}

{% block script %}
{% endblock %}

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/templates/logged_in_profile.html
{% extends 'base.html' %}
{% load  static %}
{% block title %} User Profile {% endblock %}

{% block stylesheet %}
    <style>
    .alert{ height: 50px; margin-top: 200px;}
    </style>
{% endblock %}
{% block profile %}
    <div class="fh5co-bio">
			<figure>
				<img src="{{ user.profile_picture.url }}" alt="Free HTML5 Bootstrap Template" class="img-responsive">
			</figure>
			<h3 class="heading">About Me</h3>
			<h2>{{ user.name.get_full_name }}</h2>
			<h5>{{ user.name.email }}</h5>
			<p>{{ user.details }} </p>
			<ul class="fh5co-social">
				<li><a href="#"><i class="icon-twitter"></i></a></li>
				<li><a href="#"><i class="icon-facebook"></i></a></li>
				<li><a href="#"><i class="icon-instagram"></i></a></li>
			</ul>
		</div>
{% endblock %}

{% block content %}
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}

    <div class="container">
    <a href="{% url 'blog:create' %}" class="btn btn-primary pull-right">Add new Article</a>
    <table class="table">
        <thead>
        <tr>
            <td>Title</td>
            <td>Posted_on</td>
            <td>Action</td>
        </tr>
        </thead>
        <tbody>
        {% for p in post %}
        <tr>
            <td> {{ p.title }}</td>
            <td> {{ p.posted_on }}</td>
            <td> <a href="{% url 'blog:delete' pid=p.id %}">Delete</a> || <a href="{% url 'blog:update' pid=p.id %}">Edit</a> </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>

{% endblock %}

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/templates/login.html
{% extends 'base.html' %}
{% load  static %}
{% block title %} Login Page{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel-group">
                    <div class="panel panel-default">
                      <div class="panel-heading">Please Login to your account</div>
                          <div class="panel-body">
                              {% if messages %}
                                <div class="messages">
                                    {% for message in messages %}
                                    <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
                                    {% endfor %}
                                </div>
                              {% endif %}

                              <form action="" method="POST">
                                  {% csrf_token %}
                                  <div class="form-group">
                                    <label for="email">Username:</label>
                                    <input type="text" class="form-control" name="user">
                                  </div>
                                  <div class="form-group">
                                    <label for="pwd">Password:</label>
                                    <input type="password" class="form-control" name="pass">
                                  </div>
                                  <button type="submit" class="btn btn-default">Submit</button>
                            </form>
                                Are you new here? <a href="{% url 'blog:register' %}">Register now</a>
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/templates/pdf.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
      <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ article.title }}</title>
</head>
<style>
    @page {
        size: a4 portrait;
        margin: 50px;

    }
</style>
<body>

<h1 style="text-align: center">{{ article.title }}</h1>
<img src="{{ article.image.url }}" width="250" height="66">
<p>{{ article.body|safe }}</p>


</body>
</html>

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Profile Page{% endblock %}

{% block stylesheet %}
    <style>
    #fh5co-offcanvas .fh5co-menu, #fh5co-offcanvas .fh5co-bio {width: 400px; padding: 50px;}
    </style>
{% endblock %}
{% block profile %}
	<div class="fh5co-bio">
			<figure>
				<img src="{{ auth.profile_picture.url }}" alt="Free HTML5 Bootstrap Template" class="img-responsive">
			</figure>
			<h3 class="heading">About Me</h3>
			<h2>{{ auth.name.get_full_name }}</h2>
			<p>{{ auth.details }}</p>
			<ul class="fh5co-social">
				<li><a href="#"><i class="icon-twitter"></i></a></li>
				<li><a href="#"><i class="icon-facebook"></i></a></li>
				<li><a href="#"><i class="icon-instagram"></i></a></li>
			</ul>
		</div>

{% endblock %}

{% block content %}
    <h3> Author: {{ auth.name.get_full_name }}</h3>
    {% for p in post %}
			<article class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12 animate-box">
				<figure>
					<a href="{{ p.get_single_url }}"><img src="{{ p.image.url }}" alt="Image" class="img-responsive"></a>
				</figure>
				<span class="fh5co-meta"><a href="{{ p.get_single_url }}">{{ p.category }}</a></span>
				<h2 class="fh5co-article-title"><a href="{{ p.get_single_url }}">{{ p.title }}</a></h2>
				<span class="fh5co-meta fh5co-date">{{ p.date }}</span>
			</article>
    {% endfor %}
{% endblock %}

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/templates/register.html
{% extends 'base.html' %}
{% load  static %}
{% block title %} Please Register new account{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block content %}
    <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary">Register</button>
    </form>

{% endblock %}

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/templates/single.html
{% extends 'base.html' %}
{% load  static %}
{% block title %} Single page{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block profile %}
    <div class="fh5co-bio">
			<figure>
				<img src="{{ post.article_author.profile_picture.url }}" alt="Free HTML5 Bootstrap Template" class="img-responsive">
			</figure>
			<h3 class="heading">About Me</h3>
			<h2>{{ post.article_author.name.get_full_name }}</h2>
			<h5>{{ post.article_author.name.email }}</h5>
			<p>{{ post.article_author.details }} </p>
			<ul class="fh5co-social">
				<li><a href="#"><i class="icon-twitter"></i></a></li>
				<li><a href="#"><i class="icon-facebook"></i></a></li>
				<li><a href="#"><i class="icon-instagram"></i></a></li>
			</ul>
		</div>
{% endblock %}

{% block content %}


	{% if post.id > first.id %}
        <a href="{% url 'blog:single_post' id=post.id|add:'-1' %}" class="fh5co-post-prev"><span><i class="icon-chevron-left"></i> Prev</span></a>
    {% endif %}
	{% if post.id < last.id %}
        <a href="{% url 'blog:single_post' id=post.id|add:'1' %}" class="fh5co-post-next"><span>Next <i class="icon-chevron-right"></i></span></a>
	{% endif %}

	<!-- END #fh5co-header -->
	<div class="container-fluid">
		<div class="row fh5co-post-entry single-entry">
			<article class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-12 col-xs-offset-0">
				<figure class="animate-box">
					<img src="{{ post.image.url }}" alt="Image" class="img-responsive">
				</figure>
				<span class="fh5co-meta animate-box"><a href="{{ post.get_topic_url }}">{{ post.category.name }}</a></span>
				<h2 class="fh5co-article-title animate-box">{{ post.title }}</h2>
				<span class="fh5co-meta fh5co-date animate-box">{{ post.posted_on}}</span>
				
				<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-left content-article">
					<div class="row">
						<div class="col-lg-12 cp-r animate-box">
						<p> {{ post.body }}</p>
                        </div>
                    </div>
					
					
				</div>
			</article>
		</div>

  <div class="container">
  <a href="{% url 'blog:pdf' id=post.id %}" target="_blank"> save as pdf</a>
    <h3 class="well"> Related article</h3>
        <div class="row">
        {% for r in related %}
        <div class="col-md-3">
        <figure class="animate-box">
            <a href="{% url 'blog:single_post' id=r.id %}"><img src="{{ r.image.url }}" alt="Image" class="img-responsive"></a>
            <a href="{% url 'blog:single_post' id=r.id %}"><h2 class="fh5co-article-title animate-box">{{ r.title }}</h2></a>
            <p>{{ r.body|truncatewords:15 }}</p>
        </figure>

        </div>
        {% endfor %}
    </div>
  </div>
    <h3 class="Well">Comments</h3>
    <div class="single-post-comment">
        {% for comment in comment %}
            <h4> {{ comment.name }}</h4>
            <h5> {{ comment.email }}</h5>
            <p> {{ comment.post_comment }}</p>
            {% empty %}
            <h3> Sorry no comment Found</h3>
        {% endfor %}
    </div>
    <div class="panel panel-default">
        <div class="page-header">
            <h3 class="panel-title"> Comment</h3>
        </div>
        <div class="panel-body">
          <form action="" method="POST">
              {% csrf_token %}
              {{ form.as_p }}
              <button class="btn btn-primary">Comment</button>
          </form>
        </div>
    </div>
	</div>
{% endblock %}

Bangla Tutorial Advancing Blog in Python+Django/djangoblog/templates/topics.html
{% extends 'base.html' %}
{% load static %}
{% block title %} All Topics{% endblock %}
{% block stylesheet %}
    <style>
    .alert{ height: 50px; margin-top: 200px;}
    </style>
{% endblock %}

{% block content %}


 <div class="container">
  {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}

    {% if request.user.is_authenticated %}
        {% if request.user.is_staff or request.user.is_superuser %}
        <a href="{% url 'blog:createTopic' %}" class="btn btn-primary pull-right">Add new Category</a>
        {% endif %}
    {% endif %}
    <table class="table">
        <thead>
        <tr>
            <td>Topics</td>

            {% if request.user.is_authenticated %}
                {% if request.user.is_staff or request.user.is_superuser %}
                <td>Action</td>
                {% endif %}
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for t in topic %}
        <tr>
            <td> <a href="{% url 'blog:topic' name=t.name %}">{{ t.name }}</a> </td>

              {% if request.user.is_authenticated %}
                {% if request.user.is_staff or request.user.is_superuser %}
                <td> <a href="">Delete</a> || <a href="">Edit</a>
                {% endif %}
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>


{% endblock %}